# Generated by Django 3.2.15 on 2022-08-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0003_alter_appointment_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request',
            field=models.TextField(blank=True),
        ),
    ]
